[tools]
# -- Languages
node = "latest"
python = "3.11"
go = "latest"
# julia = "latest"

# -- Tools
tree-sitter = "latest"
starship = "latest"
uv = "latest"
ripgrep = "latest"
lsd = "latest"
fd = "latest"
bat = "latest"
delta = "latest"
fzf = "latest"
lazygit = "latest"
gh = "latest"
neovim = "0.11"
usage = "latest"
ghq = "latest"

# aws-cli = "latest"
# terraform = "latest"
# pnpm = "latest"
# ghcup = "latest"
# tmux = "latest"  # macでビルド必要なことが多い

[settings]
idiomatic_version_file_enable_tools = []
